name: Deploy 02 MR Test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-02-mr-test.yml"
      - "projects/02.MR_TEST/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload 02 MR Test
        uses: actions/upload-pages-artifact@v3
        with:
          path: projects/02.MR_TEST

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
